### PR TITLE
Change network lib to lua-apclientpp

### PR DESCRIPTION
**Pull request by ScipioWright**
Opening the PR since it felt weird not to have it open, mostly.

I think it's working at this point -- just needs more testing.

I made a pre-release for it and put that on the releases page.

### CODE REVIEW

**Comment by heinermann** [comment]
There's a duplicate CheckLocationFlags function that you added.

**Comment by ScipioWright** [comment]
Not anymore there's not

**Comment by heinermann** [comment]
I'm glad we got to delete a bunch of code we don't need to manage anymore. Only thing left is the "just needs more testing" point.

**Comment by ScipioWright** [comment]
So far no one has said anything is broken at least, it's been working for me just fine in the async, and Silv had it working so maybe we just merge and release it and hope for the best?

**Comment by heinermann** [comment]
If there are no gaping issues then sure.

**Pull request merged**
